import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {testDatabase} from './database.js';
import {migrate} from '../src/db.js';
import {createAppV14} from '../src/app-v14.js';
import {readConfig} from '../src/config.js';
import {defaultSetup} from '../public/kit.js';
import {defaultCharacterProfile} from '../public/characters-model.js';
import {ARC_STARTERS} from '../src/arc-starters.js';
let database,pool,server,origin;const users={};
async function request(path,method='GET',data,who=users.owner){const response=await fetch(`${origin}${path}`,{method,headers:{...(method!=='GET'?{'Content-Type':'application/json',Origin:origin}:{}),...(who?.cookie?{Cookie:who.cookie}:{})},body:data===undefined?undefined:JSON.stringify(data)});const raw=await response.text();return{status:response.status,data:raw?JSON.parse(raw):null,cookie:response.headers.get('set-cookie')?.split(';')[0]};}
const ok=(r,status=200)=>{assert.equal(r.status,status,JSON.stringify(r.data));return r.data;};
before(async()=>{database=await testDatabase();pool=database.pool;await migrate(pool);let handler;server=createServer((req,res)=>handler(req,res));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));origin=`http://127.0.0.1:${server.address().port}`;handler=createAppV14({pool,config:{...readConfig({DATABASE_URL:'postgres://unused',PORT:'3000'}),origin},logger:()=>{}});for(const name of ['owner','player','other']){const r=await request('/api/auth/register','POST',{email:`${name}@arcs.example.test`,displayName:`Arc ${name}`,password:'Character arc integration passphrase!'},null);users[name]={...ok(r,201).user,cookie:r.cookie};}});
after(async()=>{if(server)await new Promise(resolve=>server.close(resolve));if(database)await database.close();});
function profile(setup,name='Morrow Vale'){return{...defaultCharacterProfile(setup.rules),name,attributes:Object.fromEntries(setup.rules.attributes.map(a=>[a.id,a.min])),skills:[]};}
async function fixture(){const setup=defaultSetup('fantasy','council');const ev=ok(await request('/api/events','POST',{name:'Arc gathering',setup}),201).event;for(const name of ['player','other'])await pool.query("INSERT INTO memberships(event_id,user_id,role) VALUES($1,$2,'player')",[ev.id,users[name].id]);let ch=ok(await request(`/api/events/${ev.id}/characters`,'POST',{profile:profile(setup)},users.player),201).character;ch=ok(await request(`/api/events/${ev.id}/characters/${ch.id}/submit`,'POST',{version:ch.version},users.player)).character;ch=ok(await request(`/api/events/${ev.id}/characters/${ch.id}/review`,'POST',{version:ch.version,decision:'approve',feedback:''},users.owner)).character;return{ev,ch};}

test('starter packs provide three bounded arcs for every built-in theme',()=>{for(const theme of ['fantasy','cyberpunk','wasteland']){assert.equal(ARC_STARTERS[theme].length,3);for(const arc of ARC_STARTERS[theme]){assert.ok(arc.title&&arc.startingQuestion&&arc.closingReflection);assert.equal(arc.prompts.length,3);}}});

test('organizers author choices without receiving player arc state',async()=>{const{ev,ch}=await fixture();const installed=ok(await request(`/api/events/${ev.id}/arcs/install-starter`,'POST',{}),201);assert.equal(installed.installed,3);const manager=ok(await request(`/api/events/${ev.id}/arcs`, 'GET',undefined,users.owner));assert.equal(manager.mode,'organizer');assert.equal(manager.templates.length,3);assert.equal(JSON.stringify(manager).includes(ch.id),false);const player=ok(await request(`/api/events/${ev.id}/arcs?characterId=${ch.id}`,'GET',undefined,users.player));assert.equal(player.current,null);const chosen=ok(await request(`/api/events/${ev.id}/arcs/select`,'POST',{characterId:ch.id,templateId:player.templates[0].id},users.player),201).current;assert.equal(chosen.promptStates.length,3);assert.equal((await request(`/api/events/${ev.id}/arcs?characterId=${ch.id}`,'GET',undefined,users.owner)).status,404);const managerAfter=ok(await request(`/api/events/${ev.id}/arcs`,'GET',undefined,users.owner));assert.equal(JSON.stringify(managerAfter).includes(chosen.id),false);});

test('progress supports complete skip undo stale protection end and replacement history',async()=>{const{ev,ch}=await fixture();ok(await request(`/api/events/${ev.id}/arcs/install-starter`,'POST',{}),201);let view=ok(await request(`/api/events/${ev.id}/arcs?characterId=${ch.id}`,'GET',undefined,users.player));let current=ok(await request(`/api/events/${ev.id}/arcs/select`,'POST',{characterId:ch.id,templateId:view.templates[0].id},users.player),201).current;const originalVersion=current.version;current=ok(await request(`/api/events/${ev.id}/arcs/progress`,'PATCH',{characterId:ch.id,expectedVersion:current.version,operation:'set-prompt',index:0,value:'complete'},users.player)).current;assert.equal(current.promptStates[0],'complete');assert.equal((await request(`/api/events/${ev.id}/arcs/progress`,'PATCH',{characterId:ch.id,expectedVersion:originalVersion,operation:'set-prompt',index:1,value:'skipped'},users.player)).status,409);current=ok(await request(`/api/events/${ev.id}/arcs/progress`,'PATCH',{characterId:ch.id,expectedVersion:current.version,operation:'set-prompt',index:0,value:'open'},users.player)).current;assert.equal(current.promptStates[0],'open');const firstId=current.id;current=ok(await request(`/api/events/${ev.id}/arcs/select`,'POST',{characterId:ch.id,templateId:view.templates[1].id},users.player),201).current;view=ok(await request(`/api/events/${ev.id}/arcs?characterId=${ch.id}`,'GET',undefined,users.player));assert.equal(view.current.id,current.id);assert.equal(view.history.some(h=>h.id===firstId&&h.status==='replaced'),true);current=ok(await request(`/api/events/${ev.id}/arcs/progress`,'PATCH',{characterId:ch.id,expectedVersion:current.version,operation:'set-prompt',index:1,value:'skipped'},users.player)).current;assert.equal(current.promptStates[1],'skipped');ok(await request(`/api/events/${ev.id}/arcs/progress`,'PATCH',{characterId:ch.id,expectedVersion:current.version,operation:'end'},users.player));view=ok(await request(`/api/events/${ev.id}/arcs?characterId=${ch.id}`,'GET',undefined,users.player));assert.equal(view.current,null);assert.equal(view.history.some(h=>h.status==='ended'),true);});

test('another player cannot read or mutate someone else\'s arc through character identity',async()=>{const{ev,ch}=await fixture();ok(await request(`/api/events/${ev.id}/arcs/install-starter`,'POST',{}),201);assert.equal((await request(`/api/events/${ev.id}/arcs?characterId=${ch.id}`,'GET',undefined,users.other)).status,404);const templates=ok(await request(`/api/events/${ev.id}/arcs?characterId=${ch.id}`,'GET',undefined,users.player)).templates;assert.equal((await request(`/api/events/${ev.id}/arcs/select`,'POST',{characterId:ch.id,templateId:templates[0].id},users.other)).status,404);});
