import test,{afterEach} from 'node:test';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { createExperienceStudioUI } from '../public/experience-studio-ui.js';
import { EXPERIENCE_LIBRARY } from '../public/experience-library.js';
import {newFieldAcceptance} from '../public/field-acceptance-model.js';
let dom;const original={window:globalThis.window,document:globalThis.document,navigator:Object.getOwnPropertyDescriptor(globalThis,'navigator')};
function fixture(customAPI){dom=new JSDOM('<main id="main"></main>',{url:'https://oracle.test/'});globalThis.window=dom.window;globalThis.document=dom.window.document;Object.defineProperty(globalThis,'navigator',{configurable:true,value:dom.window.navigator});dom.window.confirm=()=>true;const state={view:'detail',event:{id:'e1',name:'The gathering'},session:{user:{id:'u1'}}};const context={event:{id:'e1',name:'The gathering',themeId:'fantasy',status:'draft',version:1},drafts:[],installs:[],resources:[],characters:[],release:{version:'2.3.0',commit:'a'.repeat(40)}};const requests=[];const api=async(p,m='GET',b)=>{requests.push({p,m,b});if(p.endsWith('/experience-studio'))return context;if(customAPI)return customAPI(p,m,b);throw Error('Unexpected request '+p);};const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const ui=createExperienceStudioUI({state,api,shell:html=>document.querySelector('#main').innerHTML=html,esc,isManager:()=>true});return{ui,state,context,requests};}
const action=(ui,name,data={})=>ui.action({dataset:{action:'studio-'+name,...data}});
afterEach(()=>{dom?.window.close();globalThis.window=original.window;globalThis.document=original.document;Object.defineProperty(globalThis,'navigator',original.navigator);});
test('library leads into six real authoring steps without mutating an event',async()=>{const{ui,requests}=fixture();await ui.open();assert.equal(document.querySelectorAll('.studio-library article').length,5);await action(ui,'load',{key:EXPERIENCE_LIBRARY[0].key});assert.equal(document.querySelectorAll('.studio-steps button').length,6);for(let i=0;i<6;i++){await action(ui,'step',{step:String(i)});assert.ok(document.querySelector('.studio-editor'));}assert.equal(requests.filter(r=>r.m!=='GET').length,0);});
test('authoring text is escaped and dirty prompts protect navigation',async()=>{const{ui}=fixture();await ui.open();await action(ui,'new');const field=document.querySelector('[data-studio-path="title"]');field.value='<img src=x onerror=alert(1)>';ui.input(field);await action(ui,'step',{step:'1'});assert.equal(document.querySelectorAll('img').length,0);assert.match(document.body.textContent,/<img src=x onerror=alert\(1\)>/);window.confirm=()=>false;assert.equal(ui.confirmDiscard(),false);});
test('edits entered during a save remain unsaved after the submitted revision succeeds',async()=>{let complete;const{ui}=fixture(async(p,m,b)=>new Promise(r=>complete=()=>r({id:'d1',version:1,document:b.document})));await ui.open();await action(ui,'new');let field=document.querySelector('[data-studio-path="title"]');field.value='First submitted title';ui.input(field);const saving=action(ui,'save');await new Promise(r=>setTimeout(r,0));field=document.querySelector('[data-studio-path="title"]');field.value='Newer unsaved title';ui.input(field);complete();await saving;assert.match(document.body.textContent,/newer page edits are still unsaved/i);assert.equal(document.querySelector('[data-studio-path="title"]').value,'Newer unsaved title');window.confirm=()=>false;assert.equal(ui.confirmDiscard(),false);});
test('disconnect preserves unsaved draft text but prevents installation and server saves',async()=>{const{ui,requests}=fixture();await ui.open();await action(ui,'new');const field=document.querySelector('[data-studio-path="title"]');field.value='Keep this text';ui.input(field);ui.disconnect();await action(ui,'save');assert.equal(requests.filter(r=>r.m!=='GET').length,0);assert.equal(document.querySelector('[data-studio-path="title"]').value,'Keep this text');assert.match(document.body.textContent,/Reconnect before saving/);});
test('late private responses cannot replace a different account or event workspace',async()=>{let complete;const{ui,state}=fixture(async()=>new Promise(r=>complete=()=>r({id:'d1',version:1,document:EXPERIENCE_LIBRARY[0]})));await ui.open();const loading=action(ui,'draft',{id:'d1'});await new Promise(r=>setTimeout(r,0));state.event={id:'e2',name:'Different event'};state.session.user.id='u2';complete();await loading;assert.doesNotMatch(document.body.textContent,/The Empty Festival Seat/);assert.match(document.body.textContent,/Organizer context unavailable/);});
test('field evidence starts unrun and cannot be confused with automated acceptance',async()=>{const{ui}=fixture(async()=>({version:0,report:newFieldAcceptance('2.3.0','a'.repeat(40))}));await ui.open();await action(ui,'tab',{tab:'acceptance'});await action(ui,'report-load');assert.match(document.body.textContent,/Acceptance still open/);assert.equal(document.querySelectorAll('[data-check-field="status"]').length,12);assert.match(document.body.textContent,/Software tests and deployment do not establish/);});
