import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createServer} from 'node:http';
import {testDatabase} from './database.js';
import {migrate} from '../src/db.js';
import {createAppV23} from '../src/app-v23.js';
import {readConfig,SCHEMA_VERSION} from '../src/config.js';
import {defaultSetup} from '../public/kit.js';
import {EXPERIENCE_LIBRARY} from '../public/experience-library.js';
import {newFieldAcceptance} from '../public/field-acceptance-model.js';
let db,pool,server,origin;const users={};
async function request(path,method='GET',body,who=users.owner,headers={}){const r=await fetch(origin+path,{method,signal:AbortSignal.timeout(20000),headers:{...(who?.cookie?{Cookie:who.cookie}:{}),...(method!=='GET'?{'Content-Type':'application/json',Origin:origin}:{}),...headers},body:body===undefined?undefined:JSON.stringify(body)});return{status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0],headers:r.headers};}
const ok=(r,status=200)=>{assert.equal(r.status,status,JSON.stringify(r.data));return r.data;};
const pack=(theme='fantasy')=>structuredClone(EXPERIENCE_LIBRARY.find(p=>p.themeId===theme));
async function event(theme='fantasy'){const e=ok(await request('/api/events','POST',{name:'Studio test',setup:defaultSetup(theme,'council')}),201).event;for(const [name,role]of [['player','player'],['staff','staff'],['organizer','organizer']])await pool.query('INSERT INTO memberships(event_id,user_id,role) VALUES($1,$2,$3)',[e.id,users[name].id,role]);return e;}
const path=e=>`/api/events/${e.id}/experience-studio`;
const input=p=>({pack:p,resourceBindings:{},roleBindings:{}});
async function preview(e,p){return ok(await request(path(e)+'/preview','POST',input(p)));}
async function install(e,p){const prev=await preview(e,p);return ok(await request(path(e)+'/install','POST',{...input(p),previewToken:prev.previewToken,confirm:true,enableInstruments:true,additiveVersion:false}),201);}
before(async()=>{db=await testDatabase();pool=db.pool;assert.equal(await migrate(pool),SCHEMA_VERSION);let handler;server=createServer((req,res)=>handler(req,res));await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`;handler=createAppV23({pool,config:{...readConfig({DATABASE_URL:'postgres://unused'}),origin},logger:()=>{}});for(const name of ['owner','organizer','staff','player','outside','superuser']){const r=await request('/api/auth/register','POST',{email:`${name}@studio.test`,displayName:name,password:'Testing experience studio safely!'},null);users[name]={...ok(r,201).user,cookie:r.cookie};}await pool.query('UPDATE users SET is_superuser=true WHERE id=$1',[users.superuser.id]);});
after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));await db.close();});
test('studio current-role and expected-account guards protect all organizer material',async()=>{const e=await event();for(const name of ['owner','organizer','superuser'])assert.equal((await request(path(e),'GET',undefined,users[name])).status,200);for(const [who,status]of [[null,401],[users.player,403],[users.staff,403],[users.outside,404]])assert.equal((await request(path(e),'GET',undefined,who)).status,status);assert.equal((await request(path(e)+'?audience=organizer')).status,400);assert.equal((await request(path(e),'GET',undefined,users.owner,{'X-ORACLE-Expected-Account':users.player.id})).status,409);assert.match((await request(path(e))).headers.get('cache-control'),/private, no-store/);});
test('draft saves use revision checks, cannot cross events, and do not install anything',async()=>{const e=await event(),p=pack();const d=ok(await request(path(e)+'/drafts','POST',{document:p,version:0}),201);p.title='Edited draft';const r=ok(await request(path(e)+'/drafts/'+d.id,'PUT',{document:p,version:d.version}));assert.equal(r.version,2);assert.equal((await request(path(e)+'/drafts/'+d.id,'PUT',{document:p,version:1})).status,409);const other=await event();assert.equal((await request(path(other)+'/drafts/'+d.id)).status,404);assert.equal(ok(await request(path(e))).installs.length,0);});
test('each theme previews and installs complete authored definitions without any player records',async()=>{for(const theme of ['fantasy','cyberpunk','wasteland']){const e=await event(theme),p=pack(theme),prev=await preview(e,p);assert.equal(prev.assessment.valid,true);assert.equal(prev.changes.connectionCards,6);const body={...input(p),previewToken:prev.previewToken,confirm:true,enableInstruments:true,additiveVersion:false};const a=ok(await request(path(e)+'/install','POST',body),201);assert.ok(a.installed);const b=ok(await request(path(e)+'/install','POST',body));assert.equal(b.installed,false);assert.equal(a.id,b.id);for(const t of ['connection_assignments','connection_confirmations','character_arc_states','community_project_contributions','community_project_receipts','community_project_effects','community_project_refunds']){if(t==='connection_confirmations')continue;assert.equal((await pool.query(`SELECT count(*)::int n FROM ${t} WHERE event_id=$1`,[e.id])).rows[0].n,0,t);}assert.equal((await pool.query('SELECT status FROM community_projects WHERE id=$1',[a.mapping.projectId])).rows[0].status,'draft');const adventure=(await pool.query('SELECT definition FROM event_adventures WHERE event_id=$1',[e.id])).rows[0].definition;assert.equal(adventure.nodes.length,3);assert.ok(adventure.nodes.every(n=>!p.nodes.some(x=>x.key===n.id)));assert.ok(adventure.nodes.some(n=>n.conditions.completed.includes(a.mapping.nodes.observation)));const exported=ok(await request(path(e)+'/installs/'+a.id));assert.deepEqual(exported.document,p);assert.equal(Object.hasOwn(exported.document,'mapping'),false);}});
test('same-version mutations conflict and an additive upgrade never overwrites customized content',async()=>{const e=await event(),p=pack(),a=await install(e,p);await pool.query("UPDATE connection_templates SET title='Organizer customization',version=version+1 WHERE id=$1",[a.mapping.connections['opening-1']]);const changed=structuredClone(p);changed.title='Revised edition';let prev=await preview(e,changed);assert.equal(prev.assessment.valid,false);changed.version=2;prev=await preview(e,changed);assert.ok(prev.previous.customization.length);assert.ok(prev.previous.comparison.changes.length);const body={...input(changed),previewToken:prev.previewToken,confirm:true,enableInstruments:true,additiveVersion:false};assert.equal((await request(path(e)+'/install','POST',body)).status,409);const second=ok(await request(path(e)+'/install','POST',{...body,additiveVersion:true}),201);assert.notEqual(second.mapping.projectId,a.mapping.projectId);assert.equal((await pool.query('SELECT title FROM connection_templates WHERE id=$1',[a.mapping.connections['opening-1']])).rows[0].title,'Organizer customization');});
test('preview is tied to event state and explicit instrument activation',async()=>{const e=await event(),p=pack(),prev=await preview(e,p);const body={...input(p),previewToken:prev.previewToken,confirm:true,enableInstruments:false,additiveVersion:false};assert.equal((await request(path(e)+'/install','POST',body)).status,409);await pool.query('UPDATE events SET version=version+1 WHERE id=$1',[e.id]);assert.equal((await request(path(e)+'/install','POST',{...body,enableInstruments:true})).status,409);assert.equal(ok(await request(path(e))).installs.length,0);});
test('missing or foreign resource and role bindings fail without partial definitions',async()=>{const e=await event(),p=pack();p.resources=[{key:'supplies',name:'Supplies'}];Object.assign(p.project.milestones[0],{mode:'resource',resourceKey:'supplies',allowedEvidence:[]});let v=await preview(e,p);assert.equal(v.assessment.valid,false);assert.equal((await request(path(e)+'/preview','POST',{pack:p,resourceBindings:{supplies:'foreign'},roleBindings:{}})).status,400);p.resources=[];p.project.milestones[0]=pack().project.milestones[0];p.endingRoles=['role-1'];v=await preview(e,p);assert.equal(v.assessment.valid,false);assert.equal((await request(path(e)+'/preview','POST',{pack:p,resourceBindings:{},roleBindings:{'role-1':randomUUID()}})).status,400);assert.equal(ok(await request(path(e))).installs.length,0);});
test('installation is refused once an event is live paused ended or archived',async()=>{for(const status of ['live','paused','ended','archived']){const e=await event(),p=pack(),prev=await preview(e,p);await pool.query('UPDATE events SET status=$2 WHERE id=$1',[e.id,status]);assert.equal((await request(path(e)+'/install','POST',{...input(p),previewToken:prev.previewToken,confirm:true,enableInstruments:true,additiveVersion:false})).status,409);assert.equal((await pool.query('SELECT count(*)::int n FROM connection_templates WHERE event_id=$1',[e.id])).rows[0].n,0);}});
test('two exact simultaneous installations produce one whole set of definitions',async()=>{const e=await event(),p=pack(),prev=await preview(e,p),body={...input(p),previewToken:prev.previewToken,confirm:true,enableInstruments:true,additiveVersion:false};const outcomes=await Promise.all([request(path(e)+'/install','POST',body),request(path(e)+'/install','POST',body)]);assert.deepEqual(outcomes.map(r=>r.status).sort(),[200,201]);assert.equal((await pool.query('SELECT count(*)::int n FROM connection_templates WHERE event_id=$1',[e.id])).rows[0].n,6);});
test('acceptance reports require actual evidence for pass, use revisions, and start explicitly incomplete',async()=>{const e=await event();let r=ok(await request(path(e)+'/acceptance'));assert.equal(r.assessment.selfReportedComplete,false);const report=newFieldAcceptance('2.3.0','a'.repeat(40));report.checks[0].status='pass';assert.equal((await request(path(e)+'/acceptance','PUT',{report,version:0})).status,400);report.checks[0].status='not_run';r=ok(await request(path(e)+'/acceptance','PUT',{report,version:0}));assert.equal(r.version,1);assert.equal((await request(path(e)+'/acceptance','PUT',{report,version:0})).status,409);assert.equal((await request(path(e)+'/acceptance','GET',undefined,users.player)).status,403);});
test('rehearsal carries current authored customizations with fresh record identities and no source play or field reports',async()=>{const e=await event(),p=pack(),a=await install(e,p);await pool.query("UPDATE connection_templates SET title='Customized before copy',version=version+1 WHERE id=$1",[a.mapping.connections['opening-1']]);ok(await request(path(e)+'/acceptance','PUT',{report:newFieldAcceptance('2.3.0','a'.repeat(40)),version:0}));const copy=ok(await request(`/api/events/${e.id}/adventure/rehearsal`,'POST',{}),201).event;const installs=ok(await request(path(copy))).installs;assert.equal(installs.length,1);const c=ok(await request(path(copy)+'/installs/'+installs[0].id));assert.notEqual(c.mapping.projectId,a.mapping.projectId);assert.notEqual(c.mapping.connections['opening-1'],a.mapping.connections['opening-1']);assert.equal((await pool.query('SELECT title FROM connection_templates WHERE id=$1',[c.mapping.connections['opening-1']])).rows[0].title,'Customized before copy');assert.equal(ok(await request(path(copy)+'/acceptance')).version,0);const manage=ok(await request(`/api/events/${copy.id}/adventure/manage`));ok(await request(`/api/events/${copy.id}/adventure/reset`,'POST',{version:manage.version,confirm:true}));assert.equal((await pool.query('SELECT title FROM connection_templates WHERE id=$1',[a.mapping.connections['opening-1']])).rows[0].title,'Customized before copy');});

test('installed scenario is playable from an original discovery through reviewed community work and one ending',async()=>{
 const e=await event(),p=pack(),installed=await install(e,p),b=`/api/events/${e.id}`;
 const {defaultCharacterProfile}=await import('../public/characters-model.js');
 const chars={};
 for(const name of ['owner','player']){
  let c=ok(await request(b+'/characters','POST',{profile:{...defaultCharacterProfile(e.setup.rules),name:`Studio ${name}`}},users[name]),201).character;
  c=ok(await request(`${b}/characters/${c.id}/submit`,'POST',{version:c.version},users[name])).character;
  if(c.status!=='approved')c=ok(await request(`${b}/characters/${c.id}/review`,'POST',{version:c.version,decision:'approve',feedback:''})).character;
  chars[name]=c;
 }
 const current=ok(await request(b)).event;
 ok(await request(b,'PATCH',{version:current.version,status:'rehearsal'}));
 const a=ok(await request(b+'/adventure/manage')),node=a.definition.nodes.find(n=>n.id===installed.mapping.nodes.observation);
 const discovery=ok(await request(b+'/adventure/action','POST',{requestId:randomUUID(),characterId:chars.player.id,nodeId:node.id,version:a.version,kind:'examine',examId:node.examinations[0].id,code:node.code},users.player));
 assert.ok(discovery.journal.length);
 const projectBase=b+'/projects/'+installed.mapping.projectId;
 const detail=ok(await request(projectBase));
 ok(await request(projectBase+'/status','PATCH',{version:detail.project.version,status:'open'}));
 const eligible=ok(await request(projectBase+`/integrations?characterId=${chars.player.id}`,'GET',undefined,users.player)).evidence.find(x=>x.kind==='relic');assert.ok(eligible);
 const evidenceMilestone=detail.milestones.find(m=>m.contributionMode==='evidence');
 ok(await request(projectBase+'/evidence','POST',{requestId:randomUUID(),characterId:chars.player.id,milestoneId:evidenceMilestone.id,sourceKind:'relic',sourceId:eligible.id,summary:'Checked the authored evidence in person.'},users.player),201);
 for(const m of detail.milestones.filter(m=>m.contributionMode==='reviewed'))for(const name of ['player','owner'].slice(0,m.requiredCount)){
  const c=ok(await request(projectBase+'/contributions','POST',{requestId:randomUUID(),characterId:chars[name].id,milestoneId:m.id,routeKey:p.project.routes[0].key,summary:'Prepared the agreed scene.'},users[name]),201).contribution;
  ok(await request(projectBase+'/review','PATCH',{contributionId:c.id,version:c.version,decision:'accepted',reviewNote:'Scene confirmed.'}));
 }
 const done=ok(await request(projectBase));assert.equal(done.project.status,'completed');
 const unlocked=ok(await request(projectBase+`/unlocks?characterId=${chars.player.id}`,'GET',undefined,users.player));assert.equal(unlocked.unlocks.length,1);
 assert.equal((await pool.query("SELECT count(*)::int n FROM story_entries WHERE event_id=$1 AND status='draft' AND kind='bulletin'",[e.id])).rows[0].n,1);
 assert.equal((await pool.query("SELECT count(*)::int n FROM community_project_receipts WHERE project_id=$1 AND kind='project_complete'",[done.project.id])).rows[0].n,1);
 // Copies never inherit completion or player claims. Playing then resetting a
 // dedicated copy also must not delete the original scene's receipt.
 const copy=ok(await request(b+'/adventure/rehearsal','POST',{}),201).event;
 const copiedInstall=ok(await request(path(copy))).installs[0];
 const ci=ok(await request(path(copy)+'/installs/'+copiedInstall.id));
 assert.equal((await pool.query('SELECT status FROM community_projects WHERE id=$1',[ci.mapping.projectId])).rows[0].status,'draft');
 for(const table of ['community_project_contributions','community_project_effects','community_project_receipts','character_arc_states','connection_assignments'])assert.equal((await pool.query(`SELECT count(*)::int n FROM ${table} WHERE event_id=$1`,[copy.id])).rows[0].n,0,table);
 const manage=ok(await request(`/api/events/${copy.id}/adventure/manage`));ok(await request(`/api/events/${copy.id}/adventure/reset`,'POST',{version:manage.version,confirm:true}));
 assert.equal((await pool.query("SELECT count(*)::int n FROM community_project_receipts WHERE project_id=$1 AND kind='project_complete'",[done.project.id])).rows[0].n,1);
});

test('resource dependencies map to the destination without creating balances or changing other events',async()=>{
 const e=await event(),p=pack();await pool.query("INSERT INTO economy_resources(event_id,id,name) VALUES($1,'parts','Available repair parts')",[e.id]);
 p.resources=[{key:'supplies',name:'Supplies'}];Object.assign(p.project.milestones[0],{mode:'resource',resourceKey:'supplies',allowedEvidence:[],requiredCount:2});
 const data={pack:p,resourceBindings:{supplies:'parts'},roleBindings:{}};
 const preview=ok(await request(path(e)+'/preview','POST',data));assert.equal(preview.assessment.valid,true);
 const installed=ok(await request(path(e)+'/install','POST',{...data,previewToken:preview.previewToken,confirm:true,enableInstruments:true,additiveVersion:false}),201);
 const m=(await pool.query('SELECT resource_id,contribution_mode FROM community_project_milestones WHERE id=$1',[installed.mapping.milestones[p.project.milestones[0].key]])).rows[0];
 assert.equal(m.resource_id,'parts');assert.equal(m.contribution_mode,'resource');assert.equal((await pool.query('SELECT count(*)::int n FROM economy_balances WHERE event_id=$1',[e.id])).rows[0].n,0);
 const changed={...data,resourceBindings:{supplies:''}};assert.equal((await request(path(e)+'/install','POST',{...changed,previewToken:preview.previewToken,confirm:true,enableInstruments:true,additiveVersion:false})).status,409);
});
