import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createServer} from 'node:http';
import {testDatabase} from './database.js';
import {migrate} from '../src/db.js';
import {createAppV16} from '../src/app-v16.js';
import {readConfig} from '../src/config.js';
import {defaultSetup} from '../public/kit.js';

let database,pool,server,origin;const users={};
async function request(path,method='GET',data,who=users.owner){const r=await fetch(`${origin}${path}`,{method,headers:{...(method!=='GET'?{'Content-Type':'application/json',Origin:origin}:{}),...(who?.cookie?{Cookie:who.cookie}:{})},body:data===undefined?undefined:JSON.stringify(data)});const raw=await r.text();return{status:r.status,data:raw?JSON.parse(raw):null,cookie:r.headers.get('set-cookie')?.split(';')[0]};}
function ok(r,status=200){assert.equal(r.status,status,JSON.stringify(r.data));return r.data;}
const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let seq=0;const badge=()=>{const n=++seq;return Array.from({length:20},(_,i)=>alphabet[(i+n)%alphabet.length]).join('');};
async function fixture(){const ev=ok(await request('/api/events','POST',{name:'Batch 16 project',setup:defaultSetup('fantasy','council')}),201).event;for(const [name,role] of [['player','player'],['other','player'],['staff','staff']])await pool.query('INSERT INTO memberships(event_id,user_id,role) VALUES($1,$2,$3)',[ev.id,users[name].id,role]);const chars={};for(const name of ['player','other']){chars[name]=randomUUID();await pool.query("INSERT INTO characters(id,event_id,user_id,status,profile,badge_code,inventory_initialized) VALUES($1,$2,$3,'approved',$4,$5,true)",[chars[name],ev.id,users[name].id,JSON.stringify({name:`${name} character`}),badge()]);}
  await pool.query("INSERT INTO economy_resources(event_id,id,name) VALUES($1,'parts','Repair parts')",[ev.id]);
  await pool.query("INSERT INTO economy_balances(event_id,character_id,resource_id,quantity) VALUES($1,$2,'parts',5),($1,$3,'parts',5)",[ev.id,chars.player,chars.other]);
  await pool.query('INSERT INTO event_adventures(event_id,definition) VALUES($1,$2)',[ev.id,JSON.stringify({nodes:[{id:'lantern-relic',type:'relic'}]})]);
  const journal=randomUUID();await pool.query("INSERT INTO adventure_journal(id,event_id,character_id,node_id,entry_key,title,text,type) VALUES($1,$2,$3,'lantern-relic','relic-proof','Lantern lens notes','The lens has a service mark.','reading')",[journal,ev.id,chars.player]);
  return{ev,chars,journal};
}
before(async()=>{database=await testDatabase();pool=database.pool;await migrate(pool);let handler;server=createServer((req,res)=>handler(req,res));await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`;handler=createAppV16({pool,config:{...readConfig({DATABASE_URL:'postgres://unused',PORT:'3000'}),origin},logger:()=>{}});for(const name of ['owner','player','other','staff']){const r=await request('/api/auth/register','POST',{email:`${name}@batch16.example.test`,displayName:`Batch16 ${name}`,password:'Batch sixteen integration passphrase!'},null);users[name]={...ok(r,201).user,cookie:r.cookie};}});
after(async()=>{if(server)await new Promise(r=>server.close(r));if(database)await database.close();});

test('verified evidence, atomic donations, reviewed work, and bounded consequences share one completion path',async()=>{const f=await fixture(),base=`/api/events/${f.ev.id}/projects`;const created=ok(await request(`${base}/create`,'POST',{title:'Restore the Test Lantern',purpose:'Exercise Batch 16.',contributionRoutes:[{key:'quiet',label:'Quiet support',help:'Prepare notes.'}],milestones:[{title:'Evidence',description:'Verified discovery.',requiredCount:1,contributionMode:'evidence',allowedEvidence:['relic']},{title:'Parts',description:'Donate two parts.',requiredCount:2,contributionMode:'resource',resourceId:'parts'},{title:'Plan',description:'Reviewed plan.',requiredCount:1,contributionMode:'reviewed'}],outcomeText:'The lantern works.'}),201);const pid=created.project.id,[evidenceM,resourceM,reviewedM]=created.milestones;
  ok(await request(`${base}/${pid}/consequences`,'POST',{kind:'content_unlock',title:'Light returns',body:'The lantern now burns for the settlement.',audience:{type:'event'},position:0}),201);
  ok(await request(`${base}/${pid}/consequences`,'POST',{kind:'broadside_draft',title:'Lantern Restored',body:'The settlement restored its lantern.',audience:{type:'event'},position:1}),201);
  ok(await request(`${base}/${pid}/status`,'PATCH',{version:created.project.version,status:'open'}));
  const integrations=ok(await request(`${base}/${pid}/integrations?characterId=${f.chars.player}`,'GET',undefined,users.player));assert.ok(integrations.evidence.some(x=>x.id===f.journal&&x.kind==='relic'));assert.equal(integrations.resources.find(x=>x.id==='parts').quantity,5);
  const er=randomUUID();const evidence=ok(await request(`${base}/${pid}/evidence`,'POST',{requestId:er,characterId:f.chars.player,milestoneId:evidenceM.id,sourceKind:'relic',sourceId:f.journal,summary:'Verified service mark.'},users.player),201);assert.equal(evidence.contribution.status,'accepted');assert.equal((await request(`${base}/${pid}/evidence`,'POST',{requestId:randomUUID(),characterId:f.chars.player,milestoneId:evidenceM.id,sourceKind:'relic',sourceId:f.journal,summary:'Try counting twice.'},users.player)).status,409);
  const dr=randomUUID();const donation=ok(await request(`${base}/${pid}/donate`,'POST',{requestId:dr,characterId:f.chars.player,milestoneId:resourceM.id,quantity:2},users.player),201);assert.equal(donation.receipt.after,3);const replay=ok(await request(`${base}/${pid}/donate`,'POST',{requestId:dr,characterId:f.chars.player,milestoneId:resourceM.id,quantity:2},users.player));assert.equal(replay.replayed,true);assert.equal((await pool.query("SELECT quantity FROM economy_balances WHERE event_id=$1 AND character_id=$2 AND resource_id='parts'",[f.ev.id,f.chars.player])).rows[0].quantity,3);
  const narrative=ok(await request(`${base}/${pid}/contributions`,'POST',{requestId:randomUUID(),characterId:f.chars.other,milestoneId:reviewedM.id,routeKey:'quiet',summary:'Prepared the final watch plan.'},users.other),201).contribution;const complete=ok(await request(`${base}/${pid}/review`,'PATCH',{contributionId:narrative.id,version:narrative.version,decision:'accepted',reviewNote:'Confirmed.'},users.staff));assert.equal(complete.detail.project.status,'completed');
  assert.equal((await pool.query('SELECT count(*)::int n FROM community_project_effects WHERE project_id=$1',[pid])).rows[0].n,2);assert.equal((await pool.query("SELECT count(*)::int n FROM story_entries WHERE event_id=$1 AND kind='bulletin' AND status='draft'",[f.ev.id])).rows[0].n,1);assert.equal((await pool.query("SELECT count(*)::int n FROM community_project_receipts WHERE project_id=$1 AND kind='project_complete'",[pid])).rows[0].n,1);
  const unlocks=ok(await request(`${base}/${pid}/unlocks?characterId=${f.chars.player}`,'GET',undefined,users.player));assert.equal(unlocks.unlocks.length,1);assert.equal(unlocks.unlocks[0].title,'Light returns');
  const refunded=ok(await request(`${base}/${pid}/refund`,'POST',{contributionId:donation.contribution.id,reason:'Organizer correction after completion.'}));assert.equal(refunded.quantity,2);assert.equal((await pool.query("SELECT quantity FROM economy_balances WHERE event_id=$1 AND character_id=$2 AND resource_id='parts'",[f.ev.id,f.chars.player])).rows[0].quantity,5);assert.equal((await pool.query('SELECT status FROM community_projects WHERE id=$1',[pid])).rows[0].status,'completed');assert.equal((await pool.query('SELECT count(*)::int n FROM community_project_effects WHERE project_id=$1',[pid])).rows[0].n,2,'refund does not replay or retract consequences');
});

test('verified milestone rules cannot be bypassed by narrative submission or changed after history exists',async()=>{const f=await fixture(),base=`/api/events/${f.ev.id}/projects`;const installed=ok(await request(`${base}/install-starter`,'POST',{}),201),detail=ok(await request(`${base}/${installed.projectId}`));assert.equal(detail.milestones[0].contributionMode,'evidence');assert.ok(['resource','reviewed'].includes(detail.milestones[1].contributionMode));ok(await request(`${base}/${installed.projectId}/status`,'PATCH',{version:detail.project.version,status:'open'}));const bypass=await request(`${base}/${installed.projectId}/contributions`,'POST',{requestId:randomUUID(),characterId:f.chars.player,milestoneId:detail.milestones[0].id,routeKey:detail.project.contributionRoutes[0].key,summary:'Narrative bypass attempt.'},users.player);assert.equal(bypass.status,409);ok(await request(`${base}/${installed.projectId}/evidence`,'POST',{requestId:randomUUID(),characterId:f.chars.player,milestoneId:detail.milestones[0].id,sourceKind:'relic',sourceId:f.journal,summary:'Real evidence.'},users.player),201);assert.equal((await request(`${base}/${installed.projectId}/integrations`,'PATCH',{milestoneId:detail.milestones[0].id,contributionMode:'reviewed',allowedEvidence:[],resourceId:''})).status,409);});
