import test, { before, after } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createServer } from 'node:http';
import { testDatabase } from './database.js';
import { migrate } from '../src/db.js';
import { createAppV15 } from '../src/app-v15.js';
import { readConfig } from '../src/config.js';
import { defaultSetup } from '../public/kit.js';

let database,pool,server,origin;const users={};
async function request(path,method='GET',data,who=users.owner){const response=await fetch(`${origin}${path}`,{method,headers:{...(method!=='GET'?{'Content-Type':'application/json',Origin:origin}:{}),...(who?.cookie?{Cookie:who.cookie}:{})},body:data===undefined?undefined:JSON.stringify(data)});const raw=await response.text();return{status:response.status,data:raw?JSON.parse(raw):null,cookie:response.headers.get('set-cookie')?.split(';')[0]};}
function ok(r,status=200){assert.equal(r.status,status,JSON.stringify(r.data));return r.data;}
const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
function badge(offset){return Array.from({length:20},(_,i)=>alphabet[(i+offset)%alphabet.length]).join('');}
async function makeEvent(theme='fantasy'){const ev=ok(await request('/api/events','POST',{name:'Community project test',setup:defaultSetup(theme,'council')}),201).event;for(const [name,role] of [['player','player'],['other','player'],['staff','staff']])await pool.query('INSERT INTO memberships(event_id,user_id,role) VALUES($1,$2,$3)',[ev.id,users[name].id,role]);for(const [index,name] of ['player','other'].entries())await pool.query("INSERT INTO characters(id,event_id,user_id,status,profile,badge_code,inventory_initialized) VALUES($1,$2,$3,'approved',$4,$5,true)",[randomUUID(),ev.id,users[name].id,JSON.stringify({name:`${name} character`}),badge(index*5)]);return ev;}
async function character(ev,who){return (await pool.query("SELECT id FROM characters WHERE event_id=$1 AND user_id=$2 AND status='approved'",[ev.id,who.id])).rows[0].id;}

before(async()=>{database=await testDatabase();pool=database.pool;await migrate(pool);let handler;server=createServer((req,res)=>handler(req,res));await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));origin=`http://127.0.0.1:${server.address().port}`;handler=createAppV15({pool,config:{...readConfig({DATABASE_URL:'postgres://unused',PORT:'3000'}),origin},logger:entry=>console.error(entry)});for(const name of ['owner','player','other','staff','outsider']){const r=await request('/api/auth/register','POST',{email:`${name}@projects.example.test`,displayName:`Project ${name}`,password:'Community project integration passphrase!'},null);users[name]={...ok(r,201).user,cookie:r.cookie};}});
after(async()=>{if(server)await new Promise(resolve=>server.close(resolve));if(database)await database.close();});

test('starter project is explicit, repeat-safe, themed, and includes a lower-pressure route',async()=>{const ev=await makeEvent('fantasy'),base=`/api/events/${ev.id}/projects`;let list=ok(await request(base));assert.equal(list.projects.length,0);const first=ok(await request(`${base}/install-starter`,'POST',{}),201);assert.equal(first.installed,true);const second=ok(await request(`${base}/install-starter`,'POST',{}));assert.equal(second.installed,false);list=ok(await request(base));assert.equal(list.projects.length,1);assert.equal(list.projects[0].status,'draft');const detail=ok(await request(`${base}/${first.projectId}`));assert.ok(detail.project.contributionRoutes.some(r=>r.key==='quiet'));assert.equal(detail.milestones.length,3);const playerList=ok(await request(base,'GET',undefined,users.player));assert.equal(playerList.projects.length,0,'draft projects are not published to players');});

test('pending work never counts, stable retries are idempotent, and distinct accounts drive completion',async()=>{const ev=await makeEvent(),base=`/api/events/${ev.id}/projects`;const created=ok(await request(`${base}/create`,'POST',{title:'Raise the Signal Mast',purpose:'Restore a shared signal point.',contributionRoutes:[{key:'hands',label:'Hands-on help',help:'Help prepare or arrange the work.'},{key:'quiet',label:'Quiet support',help:'Offer notes or logistics.'}],milestones:[{title:'Ready to raise',description:'Two different players contribute.',requiredCount:2,countingRule:'distinct_accounts'}],outcomeText:'The settlement has a working signal mast.',organizerNotes:'PRIVATE organizer ending note'}),201);const id=created.project.id;ok(await request(`${base}/${id}/status`,'PATCH',{version:created.project.version,status:'open'}));const p1=await character(ev,users.player),p2=await character(ev,users.other),milestone=created.milestones[0].id;
 const requestId=randomUUID(),body={requestId,characterId:p1,milestoneId:milestone,routeKey:'quiet',summary:'Prepared a quiet logistics plan.'};const submitted=ok(await request(`${base}/${id}/contributions`,'POST',body,users.player),201).contribution;const replay=ok(await request(`${base}/${id}/contributions`,'POST',body,users.player));assert.equal(replay.replayed,true);assert.equal(replay.contribution.id,submitted.id);
 let playerDetail=ok(await request(`${base}/${id}`,'GET',undefined,users.player));assert.equal(playerDetail.milestones[0].acceptedCount,0);assert.ok(!JSON.stringify(playerDetail).includes('PRIVATE organizer ending note'));
 let staffDetail=ok(await request(`${base}/${id}`,'GET',undefined,users.staff));assert.equal(staffDetail.contributions.length,1);ok(await request(`${base}/${id}/review`,'PATCH',{contributionId:submitted.id,version:submitted.version,decision:'accepted',reviewNote:'Useful preparation.'},users.staff));
 const secondSameUser=ok(await request(`${base}/${id}/contributions`,'POST',{requestId:randomUUID(),characterId:p1,milestoneId:milestone,routeKey:'hands',summary:'Also helped stage the mast.'},users.player),201).contribution;ok(await request(`${base}/${id}/review`,'PATCH',{contributionId:secondSameUser.id,version:secondSameUser.version,decision:'accepted',reviewNote:''},users.staff));staffDetail=ok(await request(`${base}/${id}`,'GET',undefined,users.staff));assert.equal(staffDetail.milestones[0].acceptedCount,1,'two accepted submissions by one account count once');assert.equal(staffDetail.project.status,'open');
 const other=ok(await request(`${base}/${id}/contributions`,'POST',{requestId:randomUUID(),characterId:p2,milestoneId:milestone,routeKey:'hands',summary:'Secured the second set of supports.'},users.other),201).contribution;const finalReview=ok(await request(`${base}/${id}/review`,'PATCH',{contributionId:other.id,version:other.version,decision:'accepted',reviewNote:'Confirmed.'},users.staff));assert.equal(finalReview.detail.project.status,'completed');const receipts=(await pool.query("SELECT count(*)::int n FROM community_project_receipts WHERE project_id=$1 AND kind='project_complete'",[id])).rows[0].n;assert.equal(receipts,1);
 const reopen=await request(`${base}/${id}/status`,'PATCH',{version:finalReview.detail.project.version,status:'open'});assert.equal(reopen.status,409);
 const acceptedFirst=finalReview.detail.contributions.find(c=>c.id===submitted.id);const correction=ok(await request(`${base}/${id}/review`,'PATCH',{contributionId:acceptedFirst.id,version:acceptedFirst.version,decision:'declined',reviewNote:'Corrected after completion.'},users.staff));assert.equal(correction.detail.project.status,'completed','a later correction does not silently reopen completed history');assert.equal((await pool.query("SELECT count(*)::int n FROM community_project_receipts WHERE project_id=$1 AND kind='project_complete'",[id])).rows[0].n,1);
});

test('staff can review but cannot author, outsiders cannot read, and player withdrawal is bounded',async()=>{const ev=await makeEvent('cyberpunk'),base=`/api/events/${ev.id}/projects`;assert.equal((await request(`${base}/create`,'POST',{title:'No',contributionRoutes:[],milestones:[]},users.staff)).status,403);assert.equal((await request(base,'GET',undefined,users.outsider)).status,404);const installed=ok(await request(`${base}/install-starter`,'POST',{}),201);let d=ok(await request(`${base}/${installed.projectId}`));ok(await request(`${base}/${installed.projectId}/status`,'PATCH',{version:d.project.version,status:'open'}));d=ok(await request(`${base}/${installed.projectId}`));const p1=await character(ev,users.player);const c=ok(await request(`${base}/${installed.projectId}/contributions`,'POST',{requestId:randomUUID(),characterId:p1,milestoneId:d.milestones[0].id,routeKey:d.project.contributionRoutes[0].key,summary:'Made a first attempt.'},users.player),201).contribution;const withdrawn=ok(await request(`${base}/${installed.projectId}/withdraw`,'PATCH',{contributionId:c.id,version:c.version},users.player)).contribution;assert.equal(withdrawn.status,'withdrawn');assert.equal((await request(`${base}/${installed.projectId}/withdraw`,'PATCH',{contributionId:c.id,version:withdrawn.version},users.player)).status,409);});
