import { randomUUID } from 'node:crypto';
import { digest, readCookie } from './security.js';
import { transaction } from './db.js';

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const MANAGERS=new Set(['owner','organizer','superuser']);
const STARTERS={
 fantasy:[
  ['A Little Local Knowledge','You need one useful piece of local knowledge.','Someone who seems established here','I’m new to this gathering. What is one thing I should know before the lanterns are lit?','Offer a small favor in return.','Ask an organizer for a gentle introduction.'],
  ['The Remembered Crest','A symbol here feels familiar.','Someone displaying a crest, token, or faction sign','That mark looks familiar. Where did you learn it?','Share a harmless memory it brings to mind.','Ask about the symbol rather than the person.'],
  ['An Old Favor','You want to understand how favors travel here.','A trader, traveler, keeper, or host','Who would you trust with a small favor around here?','Ask what people usually offer in return.','Ask for advice only; no bargain is required.'],
  ['The Quiet Witness','You noticed something ordinary that might matter.','Someone observant or curious','Did you notice anything unusual when people arrived?','Compare one harmless detail each of you saw.','Invite them to walk with you while you talk.'],
  ['A Disputed Promise','You have heard two versions of an old promise.','Someone connected to a local group','I’ve heard two versions of the same promise. What does your side remember?','Ask what a fair version would look like now.','Frame it as history, not an accusation.'],
  ['Share the Fire','You would rather begin with companionship than business.','Anyone who is not already occupied','Mind if I join you for a moment? What brought you here?','Offer your own short answer too.','Listening counts; you do not need to volunteer.']],
 cyberpunk:[
  ['Signal Check','You need a human read before trusting the network.','A local, runner, tech, or host','What’s the one thing the network won’t tell me about this place?','Ask what signal they trust most.','Ask for one practical tip and leave it there.'],
  ['Returned Shard','A story has made an unexpected return.','Someone who deals in information','Ever have data come back after you thought it was gone?','Trade a harmless example.','Keep the question hypothetical.'],
  ['Former Partner','Another operator reminds you of an old collaborator.','A willing operator or crew member','You work like someone I used to know. Where’d you learn your trade?','Ask what makes a good partner.','Talk about technique instead of history.'],
  ['Dead Zone','There is a topic everyone seems to route around.','Someone observant','What does everybody here avoid talking about?','Ask whether that silence is caution or habit.','Ask about a physical place instead of a person.'],
  ['Conflicting Loyalties','You want to know what people protect when systems fail.','Any willing participant','When the network goes dark, who do you answer to first?','Give your own answer after theirs.','Ask what they protect rather than who they obey.'],
  ['Low-Band Hello','You want a low-pressure way into the room.','Anyone not already in a scene','I’m getting my bearings. What are you working on tonight?','Offer to help with one small thing.','Listening counts; you do not need to volunteer.']],
 wasteland:[
  ['Road Knowledge','You need advice before moving through unfamiliar ground.','A scout, traveler, settler, or host','If I had to leave before dark, which road would you warn me about?','Ask what makes it dangerous.','Ask for a landmark instead of a story.'],
  ['Salvage Favor','Useful things often move through favors.','A salvager, mechanic, trader, or neighbor','Who around here can find something when everyone else says it’s gone?','Ask what they usually want in return.','Ask only for a name or role.'],
  ['Convoy Memory','A detail here reminds you of a journey.','Another traveler','What’s the strangest thing you’ve seen on the road?','Share one brief memory of your own.','Weather, machines, or landmarks all count.'],
  ['Settlement Obligation','You want to understand what this community expects.','A resident or host','What does someone have to do before folks here consider them one of their own?','Ask who taught them that rule.','Ask about customs rather than belonging.'],
  ['Water Rumor','You heard an uncertain story about a nearby resource.','Someone curious or practical','I heard a rumor about water nearby. What rumors do you actually pay attention to?','Compare how you decide what to trust.','Make clear that the rumor may be wrong.'],
  ['Sit a Spell','You need a simple opening with no task attached.','Anyone taking a quiet moment','Mind some company? I’m trying to get the lay of the place.','Ask what has surprised them today.','Sharing silence for a moment is also fine.']]
};
const send=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
const fail=(status,message)=>{const e=new Error(message);e.status=status;throw e;};
async function body(req){let s='';for await(const c of req){s+=c;if(s.length>65536)fail(413,'Request is too large.');}try{return JSON.parse(s||'{}');}catch{fail(400,'Invalid JSON request.');}}
const clean=(v,label,max,required=true)=>{if(typeof v!=='string'||v.length>max||(required&&!v.trim()))fail(400,`${label} is invalid.`);return v.trim();};
async function userFor(pool,req,config){const token=readCookie(req,config.cookieName);if(!token)return null;return (await pool.query("SELECT u.id,u.is_superuser FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now() AND NOT u.is_disabled",[digest(token)])).rows[0]||null;}
async function membership(db,eventId,user,lock=false){if(lock)await db.query('SELECT id FROM events WHERE id=$1 FOR UPDATE',[eventId]);const r=(await db.query("SELECT e.*,CASE WHEN $3::boolean THEN 'superuser' ELSE m.role END role FROM events e LEFT JOIN memberships m ON m.event_id=e.id AND m.user_id=$2 WHERE e.id=$1 AND ($3::boolean OR m.user_id IS NOT NULL)",[eventId,user.id,user.is_superuser])).rows[0];if(!r)fail(404,'Event not found or access has been removed.');return r;}
const requireManager=e=>{if(!MANAGERS.has(e.role))fail(403,'Only an organizer can manage connection cards.');};
function project(r,userId){const s=r.snapshot;return {id:r.id,characterId:r.character_id,status:r.response_status,title:s.title,situation:s.situation,approach:s.approach,opening:s.opening,followUp:s.followUp||'',quietAlternative:s.quietAlternative||'',counterpart:s.counterpart||null,sharedFact:s.sharedFact||'',sharedFactAcceptedAt:r.shared_fact_accepted_at||null,confirmedByMe:(r.confirmed_by||[]).includes(userId),createdAt:r.created_at,updatedAt:r.updated_at};}
export function createConnectionsHandler({pool,config}){return async({req,res,path,method,user})=>{
 const m=path.match(/^\/api\/events\/([0-9a-f-]{36})\/connections(?:\/(.*))?$/i);if(!m)return false;const eventId=m[1],tail=m[2]||'';if(!UUID.test(eventId))fail(404,'Not found.');
 if(method==='GET'&&!tail){const ev=await membership(pool,eventId,user);const rows=(await pool.query("SELECT a.*,COALESCE(array_agg(c.user_id) FILTER (WHERE c.user_id IS NOT NULL),'{}') confirmed_by FROM connection_assignments a LEFT JOIN connection_confirmations c ON c.assignment_id=a.id WHERE a.event_id=$1 AND (a.assigned_user_id=$2 OR a.counterpart_user_id=$2) GROUP BY a.id ORDER BY a.created_at DESC",[eventId,user.id])).rows;const out={event:{id:ev.id,name:ev.name,theme:ev.setup?.theme?.id||'fantasy'},assignments:rows.map(r=>project(r,user.id)),manager:MANAGERS.has(ev.role)};if(out.manager){out.templates=(await pool.query('SELECT * FROM connection_templates WHERE event_id=$1 ORDER BY created_at',[eventId])).rows;out.characters=(await pool.query("SELECT id,profile->>'name' name,user_id FROM characters WHERE event_id=$1 AND status='approved' ORDER BY profile->>'name'",[eventId])).rows;}send(res,200,out);return true;}
 if(method==='POST'&&tail==='starter'){const input=await body(req);const theme=await transaction(pool,async db=>{const ev=await membership(db,eventId,user,true);requireManager(ev);const key=STARTERS[input.theme]?input.theme:(STARTERS[ev.setup?.theme?.id]?ev.setup.theme.id:'fantasy');for(const x of STARTERS[key])await db.query("INSERT INTO connection_templates(id,event_id,title,situation,approach,opening,follow_up,quiet_alternative,source_key,published) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,true) ON CONFLICT(event_id,source_key) DO NOTHING",[randomUUID(),eventId,...x,`starter:${key}:${x[0]}`]);return key;});send(res,201,{ok:true,theme});return true;}
 if(method==='POST'&&tail==='templates'){const input=await body(req);const id=await transaction(pool,async db=>{const ev=await membership(db,eventId,user,true);requireManager(ev);const id=randomUUID();await db.query('INSERT INTO connection_templates(id,event_id,title,situation,approach,opening,follow_up,quiet_alternative,shared_fact,published) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,true)',[id,eventId,clean(input.title,'Title',80),clean(input.situation,'Situation',500),clean(input.approach,'Approach',160),clean(input.opening,'Opening',500),clean(input.followUp||'','Follow-up',500,false),clean(input.quietAlternative||'','Quiet alternative',500,false),clean(input.sharedFact||'','Shared fact',500,false)]);return id;});send(res,201,{id});return true;}
 if(method==='POST'&&tail==='assign'){const input=await body(req);const id=await transaction(pool,async db=>{const ev=await membership(db,eventId,user,true);requireManager(ev);const t=(await db.query('SELECT * FROM connection_templates WHERE event_id=$1 AND id=$2 AND published',[eventId,input.templateId])).rows[0];const ch=(await db.query("SELECT id,user_id,profile->>'name' name FROM characters WHERE event_id=$1 AND id=$2 AND status='approved'",[eventId,input.characterId])).rows[0];if(!t||!ch?.user_id)fail(409,'Choose a published card and approved assigned character.');let cp=null;if(input.counterpartCharacterId){cp=(await db.query("SELECT id,user_id,profile->>'name' name FROM characters WHERE event_id=$1 AND id=$2 AND status='approved'",[eventId,input.counterpartCharacterId])).rows[0];if(!cp?.user_id||cp.id===ch.id)fail(409,'Choose a different approved counterpart.');}const snap={title:t.title,situation:t.situation,approach:t.approach,opening:t.opening,followUp:t.follow_up,quietAlternative:t.quiet_alternative,sharedFact:t.shared_fact,counterpart:cp?{characterId:cp.id,name:cp.name}:null};const id=randomUUID();await db.query('INSERT INTO connection_assignments(id,event_id,template_id,character_id,assigned_user_id,counterpart_character_id,counterpart_user_id,snapshot) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[id,eventId,t.id,ch.id,ch.user_id,cp?.id||null,cp?.user_id||null,JSON.stringify(snap)]);return id;});send(res,201,{id});return true;}
 const am=tail.match(/^([0-9a-f-]{36})\/(response|confirm)$/i);if(am&&method==='POST'){const input=await body(req);await transaction(pool,async db=>{const ev=await membership(db,eventId,user,true);const a=(await db.query('SELECT * FROM connection_assignments WHERE id=$1 AND event_id=$2 FOR UPDATE',[am[1],eventId])).rows[0];if(!a)fail(404,'Connection card not found.');const current=await db.query("SELECT id FROM characters WHERE id=$1 AND event_id=$2 AND user_id=$3 AND status='approved'",[a.character_id,eventId,a.assigned_user_id]);if(!current.rows[0])fail(409,'The original character assignment changed. Ask the organizer for a new card.');if(am[2]==='response'){if(a.assigned_user_id!==user.id)fail(403,'Only the assigned player can change this card.');if(!['kept','paused','dismissed'].includes(input.status))fail(400,'Choose keep, pause, or dismiss.');await db.query('UPDATE connection_assignments SET response_status=$1,version=version+1,updated_at=now() WHERE id=$2',[input.status,a.id]);return;}if(!a.snapshot.sharedFact||![a.assigned_user_id,a.counterpart_user_id].includes(user.id))fail(403,'This card has no shared-history proposal for you.');if(input.exactText!==a.snapshot.sharedFact)fail(409,'The shared-history wording changed. Review the exact text before agreeing.');if(a.counterpart_user_id){const cp=await db.query("SELECT id FROM characters WHERE id=$1 AND event_id=$2 AND user_id=$3 AND status='approved'",[a.counterpart_character_id,eventId,a.counterpart_user_id]);if(!cp.rows[0])fail(409,'The counterpart assignment changed. This proposal can no longer be accepted.');}await db.query('INSERT INTO connection_confirmations(assignment_id,user_id,exact_text) VALUES($1,$2,$3) ON CONFLICT(assignment_id,user_id) DO UPDATE SET exact_text=excluded.exact_text,confirmed_at=now()',[a.id,user.id,input.exactText]);const count=Number((await db.query('SELECT count(*) n FROM connection_confirmations WHERE assignment_id=$1 AND exact_text=$2',[a.id,input.exactText])).rows[0].n);if(count>=2)await db.query('UPDATE connection_assignments SET shared_fact_accepted_at=COALESCE(shared_fact_accepted_at,now()),updated_at=now() WHERE id=$1',[a.id]);});send(res,200,{ok:true});return true;}
 fail(404,'Not found.');
};}
