import { randomUUID } from 'node:crypto';
import { STARTER_EXPERIENCES } from './experience-starters.js';
import { ARC_STARTERS } from './arc-starters.js';
import { PROJECT_STARTERS } from './project-starters.js';

class ExperienceError extends Error { constructor(status,message){ super(message); this.status=status; } }
const fail=(status,message)=>{throw new ExperienceError(status,message);};
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const managers=new Set(['owner','organizer','superuser']);
const send=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
async function body(req){const chunks=[];let n=0;for await(const c of req){n+=c.length;if(n>32768)fail(413,'Request is too large.');chunks.push(c);}try{return JSON.parse(Buffer.concat(chunks).toString()||'{}');}catch{fail(400,'Invalid JSON request.');}}
async function access(db,eventId,user){if(!UUID.test(eventId))fail(404,'Event not found.');const row=(await db.query(`SELECT e.id,e.name,e.status,e.setup,CASE WHEN $2::boolean THEN 'superuser' ELSE m.role END role FROM events e LEFT JOIN memberships m ON m.event_id=e.id AND m.user_id=$1 WHERE e.id=$3 AND ($2::boolean OR m.user_id IS NOT NULL)`,[user.id,user.is_superuser===true,eventId])).rows[0];if(!row)fail(404,'Event not found or access has been removed.');return row;}
function preview(experience,project){return{key:experience.key,version:experience.version,title:experience.title,themeId:experience.themeId,duration:experience.duration,party:experience.party,opening:experience.opening,unfinishedEnding:experience.unfinishedEnding,assignmentSuggestions:experience.assignmentSuggestions,connectionCards:experience.connectionCards.map(x=>({title:x[0],situation:x[1],approach:x[2],opening:x[3],followUp:x[4],quietAlternative:x[5]})),arcs:(ARC_STARTERS[experience.themeId]||[]).map(x=>({title:x.title,summary:x.summary})),project:{title:project.title,purpose:project.purpose,milestones:project.milestones.map(x=>({title:x.title,description:x.description,mode:x.contributionMode})),outcomeText:project.outcomeText}};}
async function installProject(db,eventId,user,themeId){const starter=PROJECT_STARTERS[themeId];let project=(await db.query("SELECT * FROM community_projects WHERE event_id=$1 AND source='starter' AND theme_id=$2 AND lower(title)=lower($3)",[eventId,themeId,starter.title])).rows[0];if(project)return project.id;const projectId=randomUUID();await db.query(`INSERT INTO community_projects(id,event_id,title,purpose,contribution_routes,outcome_text,theme_id,source,status) VALUES($1,$2,$3,$4,$5,$6,$7,'starter','draft')`,[projectId,eventId,starter.title,starter.purpose,JSON.stringify(starter.routes),starter.outcomeText,themeId]);const resource=(await db.query('SELECT id FROM economy_resources WHERE event_id=$1 ORDER BY id LIMIT 1',[eventId])).rows[0]?.id||null;for(const [i,m] of starter.milestones.entries()){const mode=m.contributionMode==='resource-if-available'?(resource?'resource':'reviewed'):(m.contributionMode||'reviewed');await db.query(`INSERT INTO community_project_milestones(id,event_id,project_id,title,description,required_count,counting_rule,position,contribution_mode,resource_id,allowed_evidence) VALUES($1,$2,$3,$4,$5,$6,'distinct_accounts',$7,$8,$9,$10)`,[randomUUID(),eventId,projectId,m.title,m.description,m.requiredCount,i,mode,mode==='resource'?resource:null,JSON.stringify(mode==='evidence'?(m.allowedEvidence||[]):[])]);}for(const c of starter.consequences||[])await db.query('INSERT INTO community_project_consequences(id,event_id,project_id,kind,title,body,audience,position,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[randomUUID(),eventId,projectId,c.kind,c.title,c.body,JSON.stringify(c.audience||{type:'event'}),c.position,user.id]);return projectId;}
async function installDefinitions(db,event,user,experience){const eventId=event.id,themeId=experience.themeId;for(const x of experience.connectionCards)await db.query("INSERT INTO connection_templates(id,event_id,title,situation,approach,opening,follow_up,quiet_alternative,source_key,published) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,true) ON CONFLICT(event_id,source_key) DO NOTHING",[randomUUID(),eventId,...x,`experience:${experience.key}:v${experience.version}:connection:${x[0]}`]);for(const a of ARC_STARTERS[themeId]||[]){const exists=(await db.query("SELECT id FROM character_arc_templates WHERE event_id=$1 AND source='starter' AND theme_id=$2 AND lower(title)=lower($3)",[eventId,themeId,a.title])).rows[0];if(!exists)await db.query(`INSERT INTO character_arc_templates(id,event_id,title,summary,starting_question,prompts,closing_reflection,theme_id,source,published) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'starter',true)`,[randomUUID(),eventId,a.title,a.summary,a.startingQuestion,JSON.stringify(a.prompts),a.closingReflection,themeId]);}const projectId=await installProject(db,eventId,user,themeId);return projectId;}
export function createExperiencesHandler({pool}){return async function handle({req,res,path,method,user}){const m=path.match(/^\/api\/events\/([0-9a-f-]{36})\/experience(?:\/(preview|install))?$/i);if(!m)return false;const eventId=m[1],action=m[2]||'',event=await access(pool,eventId,user);const themeId=event.setup?.theme?.id,experience=STARTER_EXPERIENCES[themeId],project=PROJECT_STARTERS[themeId];if(!experience||!project)fail(400,'This event theme does not have a complete starter experience.');if(method==='GET'&&(!action||action==='preview')){const installs=(await pool.query('SELECT starter_key,starter_version,installed_at FROM starter_experience_installs WHERE event_id=$1 ORDER BY installed_at DESC',[eventId])).rows;const characters=(await pool.query("SELECT id,profile->>'name' name,status,user_id FROM characters WHERE event_id=$1 ORDER BY profile->>'name'",[eventId])).rows;return send(res,200,{event:{id:event.id,name:event.name,status:event.status,themeId},manager:managers.has(event.role),experience:preview(experience,project),installs,characters:managers.has(event.role)?characters:[]}),true;}
 if(method==='POST'&&action==='install'){if(!managers.has(event.role))fail(403,'Only an organizer can install a starter experience.');if(event.status==='archived')fail(409,'Archived events are read-only.');const input=await body(req);if(input.confirm!==true)fail(400,'Preview the bundle and explicitly confirm installation.');const client=await pool.connect();try{await client.query('BEGIN');await client.query('SELECT id FROM events WHERE id=$1 FOR UPDATE',[eventId]);const existing=(await client.query('SELECT * FROM starter_experience_installs WHERE event_id=$1 AND starter_key=$2 AND starter_version=$3',[eventId,experience.key,experience.version])).rows[0];if(existing){await client.query('COMMIT');return send(res,200,{installed:false,install:existing}),true;}const projectId=await installDefinitions(client,event,user,experience);const snapshot={title:experience.title,themeId,duration:experience.duration,party:experience.party,connectionCardTitles:experience.connectionCards.map(x=>x[0]),arcTitles:(ARC_STARTERS[themeId]||[]).map(x=>x.title),projectTitle:project.title,projectId,assignmentSuggestions:experience.assignmentSuggestions,unfinishedEnding:experience.unfinishedEnding};const id=randomUUID();const row=(await client.query('INSERT INTO starter_experience_installs(id,event_id,starter_key,starter_version,theme_id,snapshot,installed_by) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[id,eventId,experience.key,experience.version,themeId,JSON.stringify(snapshot),user.id])).rows[0];await client.query("INSERT INTO audit_entries(event_id,actor_id,action,details) VALUES($1,$2,'starter_experience.installed',$3)",[eventId,user.id,JSON.stringify({starterKey:experience.key,starterVersion:experience.version,projectId})]);await client.query('COMMIT');return send(res,201,{installed:true,install:row}),true;}catch(e){await client.query('ROLLBACK').catch(()=>{});throw e;}finally{client.release();}}
 fail(405,'Method not allowed.');};}
