import { randomUUID } from 'node:crypto';
import { PROJECT_STARTERS } from './project-starters.js';

class ProjectError extends Error { constructor(status,message){ super(message); this.status=status; } }
const fail=(status,message)=>{ throw new ProjectError(status,message); };
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const authors=new Set(['owner','organizer','superuser']);
const reviewers=new Set(['owner','organizer','staff','superuser']);
const mutableStates=new Set(['draft','rehearsal','live','paused']);
const clean=(value,label,max,required=true)=>{if(typeof value!=='string'||value.length>max||(required&&!value.trim())||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/.test(value))fail(400,`${label} is invalid.`);return value.trim();};
async function json(req,max=65536){const chunks=[];let n=0;for await(const c of req){n+=c.length;if(n>max)fail(413,'Request is too large.');chunks.push(c);}try{const v=JSON.parse(Buffer.concat(chunks).toString()||'{}');if(!v||typeof v!=='object'||Array.isArray(v))throw 0;return v;}catch{fail(400,'Invalid JSON request.');}}
function send(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(data===undefined?undefined:JSON.stringify(data));}
async function eventAccess(pool,eventId,user){if(!UUID.test(eventId))fail(404,'Event not found.');const {rows}=await pool.query(`SELECT e.id,e.status,e.setup,CASE WHEN $2::boolean THEN 'superuser' ELSE m.role END role FROM events e LEFT JOIN memberships m ON m.event_id=e.id AND m.user_id=$1 WHERE e.id=$3 AND ($2::boolean OR m.user_id IS NOT NULL)`,[user.id,user.is_superuser===true,eventId]);if(!rows[0])fail(404,'Event not found or access has been removed.');return rows[0];}
async function ownCharacter(db,eventId,characterId,userId,lock=false){if(!UUID.test(characterId||''))fail(404,'Character not found.');const {rows}=await db.query(`SELECT id,user_id,status,profile FROM characters WHERE event_id=$1 AND id=$2 AND user_id=$3${lock?' FOR UPDATE':''}`,[eventId,characterId,userId]);if(!rows[0]||rows[0].status!=='approved')fail(404,'An approved character assigned to you is required.');return rows[0];}
const routeInput=routes=>{if(!Array.isArray(routes)||routes.length<1||routes.length>12)fail(400,'Use between one and twelve contribution routes.');const keys=new Set();return routes.map((r,i)=>{if(!r||typeof r!=='object'||Array.isArray(r))fail(400,`Contribution route ${i+1} is invalid.`);const key=clean(r.key||`route-${i+1}`,`Route ${i+1} key`,80).toLowerCase().replace(/[^a-z0-9_-]+/g,'-');if(!key||keys.has(key))fail(400,'Contribution route keys must be unique.');keys.add(key);return{key,label:clean(r.label,`Route ${i+1} label`,120),help:clean(r.help||'',`Route ${i+1} help`,1000,false)};});};
const milestoneInput=rows=>{if(!Array.isArray(rows)||rows.length<1||rows.length>20)fail(400,'Use between one and twenty milestones.');return rows.map((m,i)=>{if(!m||typeof m!=='object'||Array.isArray(m))fail(400,`Milestone ${i+1} is invalid.`);const requiredCount=Number(m.requiredCount);if(!Number.isInteger(requiredCount)||requiredCount<1||requiredCount>1000)fail(400,`Milestone ${i+1} count is invalid.`);const countingRule=m.countingRule==='accepted_contributions'?'accepted_contributions':'distinct_accounts';return{title:clean(m.title,`Milestone ${i+1} title`,160),description:clean(m.description||'',`Milestone ${i+1} description`,2000,false),requiredCount,countingRule};});};
const projectPublic=row=>({id:row.id,title:row.title,purpose:row.purpose,contributionRoutes:row.contribution_routes,outcomeText:row.outcome_text,themeId:row.theme_id,source:row.source,status:row.status,version:row.version,completedAt:row.completed_at,createdAt:row.created_at,updatedAt:row.updated_at});
const projectOrganizer=row=>({...projectPublic(row),organizerNotes:row.organizer_notes});
const contribution=row=>({id:row.id,projectId:row.project_id,milestoneId:row.milestone_id,characterId:row.character_id,routeKey:row.route_key,summary:row.summary,status:row.status,reviewNote:row.review_note,version:row.version,reviewedAt:row.reviewed_at,createdAt:row.created_at,updatedAt:row.updated_at,...(row.character_name?{characterName:row.character_name}:{}),...(row.player_name?{playerName:row.player_name}:{})});
async function projectDetails(db,eventId,projectId,{organizer=false,review=false,userId=null}={}){
  const row=(await db.query('SELECT * FROM community_projects WHERE event_id=$1 AND id=$2',[eventId,projectId])).rows[0];if(!row)fail(404,'Community project not found.');
  const milestones=(await db.query(`SELECT m.*,
    CASE WHEN m.counting_rule='distinct_accounts' THEN count(DISTINCT c.user_id) FILTER (WHERE c.status='accepted') ELSE count(c.id) FILTER (WHERE c.status='accepted') END::int AS accepted_count,
    EXISTS(SELECT 1 FROM community_project_receipts r WHERE r.project_id=m.project_id AND r.milestone_id=m.id AND r.kind='milestone_complete') AS completed
    FROM community_project_milestones m LEFT JOIN community_project_contributions c ON c.milestone_id=m.id
    WHERE m.event_id=$1 AND m.project_id=$2 GROUP BY m.id ORDER BY m.position`,[eventId,projectId])).rows;
  let contributions=[];
  if(review) contributions=(await db.query(`SELECT c.*,ch.profile->>'name' character_name,u.display_name player_name FROM community_project_contributions c JOIN characters ch ON ch.id=c.character_id JOIN users u ON u.id=c.user_id WHERE c.event_id=$1 AND c.project_id=$2 ORDER BY c.created_at`,[eventId,projectId])).rows.map(contribution);
  else if(userId) contributions=(await db.query('SELECT * FROM community_project_contributions WHERE event_id=$1 AND project_id=$2 AND user_id=$3 ORDER BY created_at',[eventId,projectId,userId])).rows.map(contribution);
  return{project:organizer?projectOrganizer(row):projectPublic(row),milestones:milestones.map(m=>({id:m.id,title:m.title,description:m.description,requiredCount:m.required_count,countingRule:m.counting_rule,acceptedCount:m.accepted_count,complete:m.completed||m.accepted_count>=m.required_count,position:m.position})),contributions};
}
async function assessCompletion(db,eventId,projectId,actorId){
  const project=(await db.query('SELECT * FROM community_projects WHERE event_id=$1 AND id=$2 FOR UPDATE',[eventId,projectId])).rows[0];if(!project)return;
  const milestones=(await db.query(`SELECT m.id,m.required_count,m.counting_rule,CASE WHEN m.counting_rule='distinct_accounts' THEN count(DISTINCT c.user_id) FILTER (WHERE c.status='accepted') ELSE count(c.id) FILTER (WHERE c.status='accepted') END::int accepted_count FROM community_project_milestones m LEFT JOIN community_project_contributions c ON c.milestone_id=m.id WHERE m.event_id=$1 AND m.project_id=$2 GROUP BY m.id,m.required_count,m.counting_rule`,[eventId,projectId])).rows;
  for(const m of milestones)if(m.accepted_count>=m.required_count)await db.query(`INSERT INTO community_project_receipts(id,event_id,project_id,kind,milestone_id) VALUES($1,$2,$3,'milestone_complete',$4) ON CONFLICT DO NOTHING`,[randomUUID(),eventId,projectId,m.id]);
  if(project.status==='open'&&milestones.length&&milestones.every(m=>m.accepted_count>=m.required_count)){
    const receipt=await db.query(`INSERT INTO community_project_receipts(id,event_id,project_id,kind) VALUES($1,$2,$3,'project_complete') ON CONFLICT DO NOTHING RETURNING id`,[randomUUID(),eventId,projectId]);
    if(receipt.rows[0]){await db.query("UPDATE community_projects SET status='completed',completed_at=now(),version=version+1,updated_at=now() WHERE id=$1",[projectId]);await db.query("INSERT INTO audit_entries(event_id,actor_id,action,details) VALUES($1,$2,'community_project.completed',$3)",[eventId,actorId,JSON.stringify({projectId})]);}
  }
}

export function createProjectsHandler({pool}){
  return async function handle({req,res,path,method,user}){
    const match=path.match(/^\/api\/events\/([0-9a-f-]{36})\/projects(?:\/([^/]+))?(?:\/([^/]+))?$/i);if(!match)return false;
    const eventId=match[1],first=match[2]||'',second=match[3]||'',event=await eventAccess(pool,eventId,user);
    if(method==='GET'&&!first){
      const manager=authors.has(event.role),staff=reviewers.has(event.role);
      const rows=(await pool.query(`SELECT * FROM community_projects WHERE event_id=$1 ${manager?'':"AND status IN ('open','completed')"} ORDER BY created_at,title`,[eventId])).rows;
      return send(res,200,{mode:manager?'organizer':staff?'staff':'player',themeId:event.setup?.theme?.id||'fantasy',projects:rows.map(manager?projectOrganizer:projectPublic)}),true;
    }
    if(method==='POST'&&first==='install-starter'){
      if(!authors.has(event.role))fail(403,'Only an organizer can install a starter project.');if(event.status==='archived')fail(409,'Archived events are read-only.');const starter=PROJECT_STARTERS[event.setup?.theme?.id];if(!starter)fail(400,'This event theme has no starter community project.');
      const existing=(await pool.query("SELECT id FROM community_projects WHERE event_id=$1 AND source='starter' AND theme_id=$2 AND lower(title)=lower($3)",[eventId,event.setup.theme.id,starter.title])).rows[0];if(existing)return send(res,200,{installed:false,projectId:existing.id}),true;
      const client=await pool.connect();try{await client.query('BEGIN');const id=randomUUID();await client.query(`INSERT INTO community_projects(id,event_id,title,purpose,contribution_routes,outcome_text,theme_id,source,status) VALUES($1,$2,$3,$4,$5,$6,$7,'starter','draft')`,[id,eventId,starter.title,starter.purpose,JSON.stringify(starter.routes),starter.outcomeText,event.setup.theme.id]);for(const [i,m] of starter.milestones.entries())await client.query(`INSERT INTO community_project_milestones(id,event_id,project_id,title,description,required_count,counting_rule,position) VALUES($1,$2,$3,$4,$5,$6,'distinct_accounts',$7)`,[randomUUID(),eventId,id,m.title,m.description,m.requiredCount,i]);await client.query('COMMIT');return send(res,201,{installed:true,projectId:id}),true;}catch(error){await client.query('ROLLBACK').catch(()=>{});throw error;}finally{client.release();}
    }
    if(method==='POST'&&first==='create'){
      if(!authors.has(event.role))fail(403,'Only an organizer can create community projects.');if(event.status==='archived')fail(409,'Archived events are read-only.');const input=await json(req),routes=routeInput(input.contributionRoutes),milestones=milestoneInput(input.milestones),client=await pool.connect();try{await client.query('BEGIN');const id=randomUUID();await client.query(`INSERT INTO community_projects(id,event_id,title,purpose,contribution_routes,outcome_text,organizer_notes,theme_id,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'draft')`,[id,eventId,clean(input.title,'Title',120),clean(input.purpose||'','Purpose',3000,false),JSON.stringify(routes),clean(input.outcomeText||'','Outcome',3000,false),clean(input.organizerNotes||'','Organizer notes',5000,false),['fantasy','cyberpunk','wasteland'].includes(input.themeId)?input.themeId:'custom']);for(const [i,m]of milestones.entries())await client.query(`INSERT INTO community_project_milestones(id,event_id,project_id,title,description,required_count,counting_rule,position) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[randomUUID(),eventId,id,m.title,m.description,m.requiredCount,m.countingRule,i]);await client.query('COMMIT');return send(res,201,await projectDetails(pool,eventId,id,{organizer:true})),true;}catch(error){await client.query('ROLLBACK').catch(()=>{});throw error;}finally{client.release();}
    }
    if(UUID.test(first)&&method==='GET'&&!second){
      const manager=authors.has(event.role),review=reviewers.has(event.role);const detail=await projectDetails(pool,eventId,first,{organizer:manager,review,userId:review?null:user.id});if(!review&&!['open','completed'].includes(detail.project.status))fail(404,'Community project not found.');return send(res,200,{...detail,mode:manager?'organizer':review?'staff':'player'}),true;
    }
    if(UUID.test(first)&&method==='PATCH'&&second==='status'){
      if(!authors.has(event.role))fail(403,'Only an organizer can change project availability.');if(event.status==='archived')fail(409,'Archived events are read-only.');const input=await json(req);if(!Number.isInteger(input.version)||!['draft','open','closed'].includes(input.status))fail(400,'Project status update is invalid.');const current=(await pool.query('SELECT * FROM community_projects WHERE event_id=$1 AND id=$2',[eventId,first])).rows[0];if(!current)fail(404,'Community project not found.');if(current.status==='completed')fail(409,'A completed project is historical. Record later corrections without reopening it.');const row=(await pool.query('UPDATE community_projects SET status=$1,version=version+1,updated_at=now() WHERE event_id=$2 AND id=$3 AND version=$4 RETURNING *',[input.status,eventId,first,input.version])).rows[0];if(!row)fail(409,'This project changed. Refresh and try again.');return send(res,200,{project:projectOrganizer(row)}),true;
    }
    if(UUID.test(first)&&method==='POST'&&second==='contributions'){
      if(!mutableStates.has(event.status))fail(409,'Community projects are not accepting play actions in this event state.');const input=await json(req);if(!UUID.test(input.requestId||'')||!UUID.test(input.characterId||'')||!UUID.test(input.milestoneId||''))fail(400,'Contribution identity is invalid.');const client=await pool.connect();try{await client.query('BEGIN');const character=await ownCharacter(client,eventId,input.characterId,user.id,true);const project=(await client.query('SELECT * FROM community_projects WHERE event_id=$1 AND id=$2 FOR UPDATE',[eventId,first])).rows[0];if(!project||project.status!=='open')fail(409,'This community project is not open for contributions.');const milestone=(await client.query('SELECT * FROM community_project_milestones WHERE event_id=$1 AND project_id=$2 AND id=$3',[eventId,first,input.milestoneId])).rows[0];if(!milestone)fail(404,'Project milestone not found.');const routes=Array.isArray(project.contribution_routes)?project.contribution_routes:[];if(!routes.some(r=>r.key===input.routeKey))fail(400,'Choose one of this project’s contribution routes.');const existing=(await client.query('SELECT * FROM community_project_contributions WHERE event_id=$1 AND request_id=$2',[eventId,input.requestId])).rows[0];if(existing){if(existing.user_id!==user.id||existing.project_id!==first)fail(409,'This request identity was already used.');await client.query('COMMIT');return send(res,200,{contribution:contribution(existing),replayed:true}),true;}const id=randomUUID();const row=(await client.query(`INSERT INTO community_project_contributions(id,request_id,event_id,project_id,milestone_id,character_id,user_id,route_key,summary) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[id,input.requestId,eventId,first,milestone.id,character.id,user.id,input.routeKey,clean(input.summary,'Contribution summary',3000)])).rows[0];await client.query('COMMIT');return send(res,201,{contribution:contribution(row)}),true;}catch(error){await client.query('ROLLBACK').catch(()=>{});throw error;}finally{client.release();}
    }
    if(UUID.test(first)&&method==='PATCH'&&second==='withdraw'){
      const input=await json(req);if(!UUID.test(input.contributionId||'')||!Number.isInteger(input.version))fail(400,'Contribution update is invalid.');const row=(await pool.query(`UPDATE community_project_contributions SET status='withdrawn',version=version+1,updated_at=now() WHERE event_id=$1 AND project_id=$2 AND id=$3 AND user_id=$4 AND version=$5 AND status='submitted' RETURNING *`,[eventId,first,input.contributionId,user.id,input.version])).rows[0];if(!row)fail(409,'Only your currently submitted contribution can be withdrawn. Refresh and try again.');return send(res,200,{contribution:contribution(row)}),true;
    }
    if(UUID.test(first)&&method==='PATCH'&&second==='review'){
      if(!reviewers.has(event.role))fail(403,'Only event staff can review project contributions.');if(!mutableStates.has(event.status))fail(409,'Project review is unavailable in this event state.');const input=await json(req);if(!UUID.test(input.contributionId||'')||!Number.isInteger(input.version)||!['accepted','declined'].includes(input.decision))fail(400,'Review decision is invalid.');const client=await pool.connect();try{await client.query('BEGIN');await client.query('SELECT id FROM community_projects WHERE event_id=$1 AND id=$2 FOR UPDATE',[eventId,first]);const current=(await client.query('SELECT * FROM community_project_contributions WHERE event_id=$1 AND project_id=$2 AND id=$3 FOR UPDATE',[eventId,first,input.contributionId])).rows[0];if(!current)fail(404,'Contribution not found.');if(current.version!==input.version)fail(409,'This contribution changed. Refresh and try again.');if(!['submitted','accepted','declined'].includes(current.status))fail(409,'This contribution is no longer reviewable.');const row=(await client.query(`UPDATE community_project_contributions SET status=$1,review_note=$2,reviewed_by=$3,reviewed_at=now(),version=version+1,updated_at=now() WHERE id=$4 RETURNING *`,[input.decision,clean(input.reviewNote||'','Review note',2000,false),user.id,current.id])).rows[0];await assessCompletion(client,eventId,first,user.id);await client.query('COMMIT');return send(res,200,{contribution:contribution(row),detail:await projectDetails(pool,eventId,first,{organizer:authors.has(event.role),review:true})}),true;}catch(error){await client.query('ROLLBACK').catch(()=>{});throw error;}finally{client.release();}
    }
    fail(405,'Method not allowed.');
  };
}
